### ISSUE TITLE
transactionReceipt depreciation

### ISSUE THREAD

**Issue by EralpB** [youknowone/itunes-iap#13]
Now that transactionReceipt is depreceated at iOS7 what is your recommended way of getting receipt-data for a transaction?

Thanks.

**Comment by misalabs** [comment]
The problem is not related with the library. Whatever, this link may help you http://stackoverflow.com/questions/18903879/transactionreceipt-for-in-app-purchase-is-deprecated-in-ios-7-what-can-i-replac

**Comment by youknowone** [comment]
Hi! Though it is not directly related to this project, still it remained a problem that this project is using deprecated, old method. I am regarding to add new API fit for new receipt-data.
