### ISSUE TITLE
Requests POST "verify=False"

### ISSUE THREAD

**Issue by AdrienCog** [youknowone/itunes-iap#16]
What is your reason to use the field "verify=False" on your request?
I use pretty much the same code to validate receipt (without this field), but recently I had several SSL errors (Bad handshake). I hope this field can help fix this.

**Comment by youknowone** [comment]
I have no idea right now. It wasn't working correctly with verify=True when I firstly wrote the code before.

**Comment by youknowone** [comment]
The default option is now verify=True and suggesting an option to set it False
