### ISSUE TITLE
Environment.pop TypeError

### ISSUE THREAD

**Issue by ilardm** [youknowone/itunes-iap#33]
Is it a typo to pop `None` index instead of `not None`?

https://github.com/youknowone/itunes-iap/blob/9a542876159c85376292e20e0c6de3d2ae1a4c6c/itunesiap/environment.py#L31

**Comment by youknowone** [comment]
Yes, it was. And it means... the code is never used!

**Comment by youknowone** [comment]
Thanks for the report. I removed it and deprecated the entire global environment stack.
