### ISSUE TITLE
aiodns dependency v1.1.1 doesn't install on m1 macs

### ISSUE THREAD

**Issue by emmilco** [youknowone/itunes-iap#65]
`aiodns` has fixed in this v3.0.0  by bumping its `pycares` dependency.  I've put up a PR https://github.com/youknowone/itunes-iap/pull/64 to bump the version.

**Comment by youknowone** [comment]
I am sorry for the late response. I released 2.6.1 https://pypi.org/project/itunes-iap/2.6.1/
