### ISSUE TITLE
UnboundLocalError: local variable 'e' referenced before assignment

### ISSUE THREAD

**Issue by misalabs** [youknowone/itunes-iap#8]
Hello everyone!

I have an 'UnboundLocalError' when I send an invalid receipt and put the 'sandbox' mode. 

>>> from itunesiap import Request, set_verification_mode
>>> set_verification_mode('sandbox')
>>> Request('').use_sandbox
True
>>> request = Request('testinvalidreceipt')
>>> request.verify()
{"password": "", "receipt-data": "testinvalidreceipt"}
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/myuser/envs/myenv/local/lib/python2.7/site-packages/itunesiap/core.py", line 98, in verify
    raise e # raise original error
UnboundLocalError: local variable 'e' referenced before assignment

**Comment by youknowone** [comment]
Thanks for report. It is updated now.

**Comment by misalabs** [comment]
Very fast! thanks a lot.
